name: hEssentials
version: 1.0.2
api-version: 1.13
author: Hempfest
depend: [ Vault, HempCore ]
soft-depend: [ PlaceholderAPI , hEssentialsChat ]
description: A lightweight alternative to EssentialsX
main: org.spigotmc.hessentials.HempfestEssentials