name: hEssentials
version: 1.1.0
api-version: 1.16
author: Hempfest
description: A lightweight alternative to EssentialsX
main: org.spigotmc.hessentials.HempfestEssentials
commands:
  gamemode:
    aliases: [hgm, hgamemode, gm]
    description: Change a players gamemode.
  teleportrequest:
    aliases: [tpr, htpr, tpre]
    description: Request to teleport to a player.