name: hEssentials
version: 2.0.3
api-version: 1.13
authors: [ Hempfest, Modify, Coolmike, Allstreamer ]
depend: [ HempCore ]
soft-depend: [ Vault, PlaceholderAPI , hEssentialsChat ]
description: A lightweight alternative to EssentialsX
main: org.spigotmc.hessentials.HempfestEssentials