name: hEssentials
version: 2.1.2
api-version: 1.13
authors:
  - Hempfest
  - Modify
  - Coolmike35
depend: [ HempCore ]
soft-depend: [ Vault, PlaceholderAPI , hEssentialsChat ]
description: A lightweight alternative to EssentialsX
main: org.spigotmc.hessentials.HempfestEssentials