name: hEssentials
version: 1.0.2
api-version: 1.13
author: Hempfest
depend: [ HempCore ]
soft-depend: [ Vault, PlaceholderAPI , hEssentialsChat ]
description: A lightweight alternative to EssentialsX
main: org.spigotmc.hessentials.HempfestEssentials